# Generated by Django 5.2 on 2025-05-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='body',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='review',
            name='body',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=8192, verbose_name='commentaire'),
        ),
    ]
