# Generated by Django 5.2 on 2025-05-01 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_body_ticket_desc_remove_review_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='starting_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
