# Generated by Django 5.2 on 2025-05-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_userfollows_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_review', to='reviews.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_ticket', to='reviews.ticket'),
        ),
    ]
