# Generated by Django 5.2 on 2025-05-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='topic',
        ),
    ]
